---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout

      # IGNORE: Retrieves node_modules cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: install-npm
          command: npm install

      # IGNORE: Caches node_modules folder
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: es-lint
          command: npm run eslint *.js

      - run:
          name: my-tests
          command: npm test

      - run:
          name: bundle
          command: npm run bundle

      - store_artifacts:
          path: ~/repo/calculator